### ISSUE TITLE
Error running main_code.py

### ISSUE THREAD

**Issue by pgleeson** [rahmielibol/ModellingNAcc#1]
I tried running the main script, and the simulations completed, but there was an error writing some of the results. This line: https://github.com/rahmielibol/ModellingNAcc/blob/ff04c8d7cedf140b052fb6629a3779fa01ca2ef9/main_code.py#L1358 mentions fr_cortex, but it's not defined elsewhere.

**Comment by rahmielibol** [comment]
Dear Padraig Gleeson,

I have taken many different types of data related to the code and I have used it to analyze. There is a passage that I forgot to delete. Thank you for your warning. I hope that it run smoothly now.

**Comment by pgleeson** [comment]
Great! Works for me now. Thanks.
